[tools]
nodejs = "latest"
lua = "latest"
python = "latest"
ruby = "latest"
rust = "latest"

# plugin for mise itself for shell completion of mise commands
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
python.uv_venv_auto = true
