add_newline = true

# For git_status:
#   !   Modified
#   ✘   Deleted
#   ⇡   Ahead
#   ⇣   Behind
#   +   Staged
#   $   Stashed changes
format = """
$directory($git_branch)($git_status)$ruby
$character """

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
